#!/usr/bin/env node
/**
 * ResultX Design System — Token build pipeline
 *
 * Reads the CSS token sources (tokens-base.css + tokens.css) and emits
 * consumer-specific outputs:
 *   - dist/tokens.theme.css  → Tailwind v4 @theme inline + runtime themes
 *   - dist/tokens.ts         → TypeScript const exports
 *
 * tokens.css remains the authoritative source. This script NEVER writes back
 * to tokens.css — edit tokens.css by hand and re-run `npm run build:tokens`.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const BASE_CSS = path.join(ROOT, 'tokens', 'base', 'tokens-base.css');
const TOKENS_CSS = path.join(ROOT, 'tokens', 'tokens.css');
const SHARED_LAYER_CSS = path.join(ROOT, 'tokens', 'themes', '_data-layer-shared.css');
const PREMIUM_LIGHT_CSS = path.join(ROOT, 'tokens', 'themes', 'premium-light.css');
const SOBER_DARK_CSS = path.join(ROOT, 'tokens', 'themes', 'sober-dark.css');
const VIBRANT_DARK_CSS = path.join(ROOT, 'tokens', 'themes', 'vibrant-dark.css');
const DIST_DIR = path.join(ROOT, 'dist');
const OUT_THEME = path.join(DIST_DIR, 'tokens.theme.css');
const OUT_TS = path.join(DIST_DIR, 'tokens.ts');

// ─────────────────────────────────────────────────────────────────────────────
// Parser — reuses balance-tracking strategy from tests/tokens.test.js
// ─────────────────────────────────────────────────────────────────────────────

function extractBlock(css, selector) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(escaped + '\\s*\\{', 'g');
  const match = re.exec(css);
  if (!match) return null;
  let depth = 1;
  let pos = match.index + match[0].length;
  const start = pos;
  while (pos < css.length && depth > 0) {
    if (css[pos] === '{') depth++;
    if (css[pos] === '}') depth--;
    pos++;
  }
  return css.slice(start, pos - 1);
}

function extractTokens(blockContent) {
  if (!blockContent) return [];
  const tokens = [];
  const seen = new Set();
  const re = /--([\w-]+)\s*:\s*([^;]+);/g;
  let m;
  while ((m = re.exec(blockContent)) !== null) {
    const name = m[1];
    const value = m[2].replace(/\s+/g, ' ').trim();
    if (!seen.has(name)) {
      seen.add(name);
      tokens.push({ name, value });
    }
  }
  return tokens;
}

// ─────────────────────────────────────────────────────────────────────────────
// Classifier — maps source tokens to Tailwind v4 @theme categories
// ─────────────────────────────────────────────────────────────────────────────

const COLOR_VALUE_RE = /^#|^rgba?\(|^hsla?\(|^oklch\(|^oklab\(|^transparent$|^currentColor$/i;

function classify(name, value) {
  if (COLOR_VALUE_RE.test(value)) return 'color';
  if (/^font-(heading|body|sans|mono|serif)$/.test(name)) return 'font';
  if (/^text-/.test(name) && /(rem|px|em)$/.test(value)) return 'text';
  if (/^weight-/.test(name) && /^\d+$/.test(value.trim())) return 'font-weight';
  if (/^leading-/.test(name)) return 'leading';
  if (/^tracking-/.test(name)) return 'tracking';
  if (/^space-/.test(name)) return 'spacing';
  if (/^radius-/.test(name)) return 'radius';
  if (/^shadow-/.test(name)) return 'shadow';
  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Generators
// ─────────────────────────────────────────────────────────────────────────────

function formatDecls(tokens, indent = '  ') {
  return tokens.map(({ name, value }) => `${indent}--${name}: ${value};`).join('\n');
}

function generateThemeInline(sharedTokens, darkTokens) {
  const lines = ['@theme inline {'];
  lines.push('  /* Auto-classified tokens exposed as Tailwind v4 utilities. */');
  lines.push('  /* Uses var() references so runtime theme switching keeps working. */');

  const categories = new Map();
  // Theme-aware tokens come from dark (dark is the DS default).
  // Shared tokens (typography, spacing, radius, shadows) come from sharedTokens.
  const classifyInto = (token) => {
    const cls = classify(token.name, token.value);
    if (!cls) return;
    if (!categories.has(cls)) categories.set(cls, new Set());
    categories.get(cls).add(token.name);
  };
  for (const t of sharedTokens) classifyInto(t);
  for (const t of darkTokens) classifyInto(t);

  const order = ['color', 'font', 'font-weight', 'text', 'leading', 'tracking', 'spacing', 'radius', 'shadow'];
  for (const prefix of order) {
    if (!categories.has(prefix)) continue;
    const names = [...categories.get(prefix)].sort();
    lines.push(`\n  /* ${prefix} (${names.length}) */`);
    for (const n of names) {
      lines.push(`  --${prefix}-${n}: var(--${n});`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

function generateTailwindTheme({ shared, dark, light, premiumLight, soberDark, vibrantDark }) {
  const header = `/*
 * ResultX Design System — Tailwind v4 theme
 * Auto-generated by scripts/build-tokens.js — DO NOT EDIT
 *
 * Usage in a Tailwind v4 consumer (e.g. Next.js 16 + Tailwind v4):
 *   @import "tailwindcss";
 *   @import "resultx-design-system/tokens/theme";
 *
 * Exposes color, typography, spacing, radius, and shadow tokens as
 * Tailwind utility classes. Runtime theme switching via
 * [data-theme="dark"|"light"|"premium-light"|"sober-dark"|"vibrant-dark"]
 * continues to work.
 */`;

  const themeInline = generateThemeInline(shared, dark);
  const sharedBlock = `:root {\n${formatDecls(shared)}\n}`;
  const darkBlock = `[data-theme="dark"] {\n${formatDecls(dark)}\n}`;
  const lightBlock = `[data-theme="light"] {\n${formatDecls(light)}\n}`;
  const premiumLightBlock = `[data-theme="premium-light"] {\n${formatDecls(premiumLight)}\n}`;
  const soberDarkBlock = `[data-theme="sober-dark"] {\n${formatDecls(soberDark)}\n}`;
  const vibrantDarkBlock = `[data-theme="vibrant-dark"] {\n${formatDecls(vibrantDark)}\n}`;
  const fallbackDark = `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n${formatDecls(dark, '    ')}\n  }\n}`;
  const fallbackLight = `@media (prefers-color-scheme: light) {\n  :root:not([data-theme]) {\n${formatDecls(light, '    ')}\n  }\n}`;

  return [
    header, '',
    themeInline, '',
    sharedBlock, '',
    darkBlock, '',
    lightBlock, '',
    premiumLightBlock, '',
    soberDarkBlock, '',
    vibrantDarkBlock, '',
    fallbackDark, '',
    fallbackLight, '',
  ].join('\n');
}

function generateTypeScript({ shared, dark, light, premiumLight, soberDark, vibrantDark }) {
  const toObj = (tokens) => {
    const entries = tokens.map(({ name, value }) => `  ${JSON.stringify(name)}: ${JSON.stringify(value)}`);
    return `{\n${entries.join(',\n')}\n}`;
  };

  return `/**
 * ResultX Design System — Token exports
 * Auto-generated by scripts/build-tokens.js — DO NOT EDIT
 *
 * For JS/TS consumers (charts, inline styles, storybook, tests):
 *   import { darkTokens, lightTokens, premiumLightTokens,
 *            soberDarkTokens, vibrantDarkTokens } from 'resultx-design-system/tokens/ts';
 */

export const sharedTokens = ${toObj(shared)} as const;

export const darkTokens = ${toObj(dark)} as const;

export const lightTokens = ${toObj(light)} as const;

export const premiumLightTokens = ${toObj(premiumLight)} as const;

export const soberDarkTokens = ${toObj(soberDark)} as const;

export const vibrantDarkTokens = ${toObj(vibrantDark)} as const;

export type SharedTokenName = keyof typeof sharedTokens;
export type ThemeTokenName =
  | keyof typeof darkTokens
  | keyof typeof lightTokens
  | keyof typeof premiumLightTokens
  | keyof typeof soberDarkTokens
  | keyof typeof vibrantDarkTokens;
export type TokenName = SharedTokenName | ThemeTokenName;

export type ThemeId =
  | "dark"
  | "light"
  | "premium-light"
  | "sober-dark"
  | "vibrant-dark";
`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Main
// ─────────────────────────────────────────────────────────────────────────────

function main() {
  const baseCss = fs.readFileSync(BASE_CSS, 'utf8');
  const tokensCss = fs.readFileSync(TOKENS_CSS, 'utf8');
  const sharedLayerCss = fs.readFileSync(SHARED_LAYER_CSS, 'utf8');
  const premiumLightCss = fs.readFileSync(PREMIUM_LIGHT_CSS, 'utf8');
  const soberDarkCss = fs.readFileSync(SOBER_DARK_CSS, 'utf8');
  const vibrantDarkCss = fs.readFileSync(VIBRANT_DARK_CSS, 'utf8');

  const baseShared = extractTokens(extractBlock(baseCss, ':root'));
  const appShared = extractTokens(extractBlock(tokensCss, ':root'));
  const dataLayerShared = extractTokens(extractBlock(sharedLayerCss, ':root'));
  const dark = extractTokens(extractBlock(tokensCss, '[data-theme="dark"]'));
  const light = extractTokens(extractBlock(tokensCss, '[data-theme="light"]'));
  const premiumLight = extractTokens(extractBlock(premiumLightCss, '[data-theme="premium-light"]'));
  const soberDark = extractTokens(extractBlock(soberDarkCss, '[data-theme="sober-dark"]'));
  const vibrantDark = extractTokens(extractBlock(vibrantDarkCss, '[data-theme="vibrant-dark"]'));

  // Merge shared: data-layer-shared overrides app overrides base
  const sharedMap = new Map();
  for (const t of baseShared) sharedMap.set(t.name, t);
  for (const t of appShared) sharedMap.set(t.name, t);
  for (const t of dataLayerShared) sharedMap.set(t.name, t);
  const shared = [...sharedMap.values()];

  if (!fs.existsSync(DIST_DIR)) fs.mkdirSync(DIST_DIR, { recursive: true });

  const themePayload = { shared, dark, light, premiumLight, soberDark, vibrantDark };
  fs.writeFileSync(OUT_THEME, generateTailwindTheme(themePayload), 'utf8');
  fs.writeFileSync(OUT_TS, generateTypeScript(themePayload), 'utf8');

  console.log(
    `✓ dist/tokens.theme.css (${shared.length} shared + ${dark.length} dark + ${light.length} light + ${premiumLight.length} premium-light + ${soberDark.length} sober-dark + ${vibrantDark.length} vibrant-dark tokens)`
  );
  console.log(`✓ dist/tokens.ts`);
}

main();
